export const KEYVALUE_LOADING = "KEYVALUE_LOADING";
export const KEYVALUE_ERR = "KEYVALUE_ERR";
export const KEYVALUE_CHECK_IF_PARAM_EXISTS = "KEYVALUE_CHECK_IF_PARAM_EXISTS";
export const KEYVALUE_GET_PARAM_VALUES = "KEYVALUE_GET_PARAM_VALUES";
export const KEYVALUE_START_SIGNAL = "KEYVALUE_START_SIGNAL";
export const KEYVALUE_FINISH_SIGNAL = "KEYVALUE_FINISH_SIGNAL";
export const KEYVALUE_ADD_ERROR = "KEYVALUE_ADD_ERROR";
export const KEYVALUE_ADD_SUCCESS = "KEYVALUE_ADD_SUCCESS";
