export const KEYVALUE_LOADING = "KEYVALUE_LOADING";
export const KEYVALUE_ERR = "KEYVALUE_ERR";
export const KEYVALUE_CHECK_IF_PARAM_EXISTS = "KEYVALUE_CHECK_IF_PARAM_EXISTS";
export const KEYVALUE_GET_PARAM_VALUES = "KEYVALUE_GET_PARAM_VALUES";
export const KEYVALUE_START_SIGNAL = "KEYVALUE_START_SIGNAL";
export const KEYVALUE_FINISH_SIGNAL = "KEYVALUE_FINISH_SIGNAL";
export const KEYVALUE_ADD_ERROR = "KEYVALUE_ADD_ERROR";
export const KEYVALUE_ADD_SUCCESS = "KEYVALUE_ADD_SUCCESS";
export const KEYVALUE_ADD_LOADING = "KEYVALUE_ADD_LOADING";

export const EDUPLAN_LOADING = "EDUPLAN_LOADING";
export const EDUPLAN_ERR = "EDUPLAN_ERR";
export const EDUPLAN_START_SIGNAL = "EDUPLAN_START_SIGNAL";
export const EDUPLAN_FINISH_SIGNAL = "EDUPLAN_FINISH_SIGNAL";
export const EDUPLAN_GET_EDUPLANS = "EDUPLAN_GET_EDUPLANS";

export const EDUPLAN_GET_PARAM_VALUES = "EDUPLAN_GET_PARAM_VALUES";
export const EDUPLAN_GET_PARAM_VALUES_SCHOOLINGYEAR =
  "EDUPLAN_GET_PARAM_VALUES_SCHOOLINGYEAR";
export const EDUPLAN_GET_PARAM_VALUES_CLASSLETTER =
  "EDUPLAN_GET_PARAM_VALUES_CLASSLETTER";

export const EDUPLAN_ADD_ERR = "EDUPLAN_ADD_ERR";
export const EDUPLAN_ADD_START_SIGNAL = "EDUPLAN_ADD_START_SIGNAL";
export const EDUPLAN_ADD_FINISH_SIGNAL = "EDUPLAN_ADD_FINISH_SIGNAL";
export const EDUPLAN_ADD_EDUPLAN = "EDUPLAN_ADD_EDUPLAN";
export const EDUPLAN_GET_EDUPLAN_SINGLE = "EDUPLAN_GET_EDUPLAN_SINGLE";
export const EDUPLAN_GET_EDUPLAN_SINGLE_ERROR =
  "EDUPLAN_GET_EDUPLAN_SINGLE_ERROR";

export const EDUPLAN_ADD_EDUPLANDATA = "EDUPLAN_ADD_EDUPLANDATA";
export const EDUPLAN_GET_EDUPLANDATA = "EDUPLAN_GET_EDUPLANDATA";
